### ISSUE TITLE
Copyright headers assume copyright assignment to HashiCorp

### ISSUE THREAD

**Issue by nemobis** [hashicorp/copywrite#100]
The bot is creating PRs with headers like
> Copyright (c) HashiCorp, Inc.

which appear to assume HashiCorp is the sole copyright holder for all files. How does the bot check that external contributors assigned copyright to HashiCorp?

For example this PR seems definitely incorrect: https://github.com/hashicorp/terraform-provider-azurerm/pull/22657#issuecomment-1755600939

For reference see also https://reuse.software/faq/#copyright-holder-author

**Comment by nemobis** [comment]
The  @hashicorp-cla bot which enforces https://www.hashicorp.com/cla on PRs is active on some but not all HashiCorp repositories, as far as I can tell. The copywrite bot should check whether and when the CLA bot was activated and started enforcing a copyright assignment on the repository. Copyright headers should then specify the years for which HashiCorp is actually known to be the copyright holders.

**Comment by crw** [comment]
Thanks for your feedback, we have passed it on to our legal team for review. If it is decided a change needs to be made, we will open a new issue at that time. Thanks again for your feedback!
