### ISSUE TITLE
Callout setup-copywrite Usage with Major Version Tag or Commit SHA

### ISSUE THREAD

**Issue by bflad** [hashicorp/copywrite#14]
## Description

HashiCorp repositories with GitHub Actions workflows will soon be enforced to use commit SHA pinning in `uses:` to curb potential supply chain issues. Currently the `README.md` section on GitHub Actions points to `@main` for using setup-copywrite.

Annoying to update (🙁 ) but I'm guessing the preference for the documentation would be to suggest:

```yaml
uses: hashicorp/setup-copywrite@3ace06ad72e6ec679ea8572457b17dbc3960b8ce # v1.0.0
```

Or (less securely):

```yaml
uses: hashicorp/setup-copywrite@v1.0.0
```

Either which way though, Dependabot should suggest version updates.

**Comment by CalebAlbers** [comment]
Great call out! PR incoming
