### ISSUE TITLE
`header_ignore` pattern not reflected

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/copywrite#18]
I tried onboarding this repository https://github.com/hashicorp/vscode-terraform and added `testFixture/` into the ignorelist:

```hcl
schema_version = 1

project {
  license        = "MPL-2.0"
  copyright_year = 2016

  header_ignore = [
    ".vscode-test",
    ".vscode-test-web",
    "out/",
    "node_modules/",
    "syntaxes/",
    "testFixture/",
  ]
}
```

Despite that `copywrite headers` attempts to add the header to files under that path:

```
copywrite headers --plan
Executing in dry-run mode. Rerun without the `--plan` flag to apply changes.

Using license identifier: MPL-2.0

Exempting the following search patterns:
.vscode-test
.vscode-test-web
out/
node_modules/
syntaxes/
testFixture/

The following files are missing headers:
...
2023-01-31T17:22:18.563Z [INFO]  cli: testFixture/actions.tf
2023-01-31T17:22:18.563Z [INFO]  cli: testFixture/modules/sample.tf
2023-01-31T17:22:18.564Z [INFO]  cli: testFixture/sample.tf
Error: missing license header
```

Is this a bug?

**Comment by CalebAlbers** [comment]
Hey @radeksimko,

Copywrite uses [doublestar](https://github.com/bmatcuk/doublestar) for the `header_ignore` globs, which differs from the `.gitignore` format. Can you try appending `**` after the forward slash for any folders you wish to ignore?

```hcl
schema_version = 1

project {
  license        = "MPL-2.0"
  copyright_year = 2016

  header_ignore = [
    ".vscode-test",
    ".vscode-test-web",
    "out/**",
    "node_modules/**",
    "syntaxes/**",
    "testFixture/**",
  ]
}
```

I just cloned the `vscode-terraform` repo and used that config, and copywrite is now correctly skipping the files:

```
2023-01-31T11:21:57.338-0800 [INFO]  cli: skipping: testFixture/modules/sample.tf
2023-01-31T11:21:57.338-0800 [INFO]  cli: skipping: testFixture/sample.tf
2023-01-31T11:21:57.338-0800 [INFO]  cli: skipping: testFixture/shasumtest.txt
```

**Comment by radeksimko** [comment]
I see! That worked, thanks!

I did read the docs but didn't realise the `**` notation is _necessary_ in such a context, I thought it was just an option.
It may be worth documenting that for extra clarity as I imagine ignoring whole directories can be a common ask?

**Comment by CalebAlbers** [comment]
Awesome, I'm glad that did the trick!

Adding some additional context to the docs is a good idea, especially since doublestar supports some more [complex patterns](https://github.com/bmatcuk/doublestar#patterns). I'm making some doc updates today and will get that added in.

Thanks!
