### ISSUE TITLE
Allow suppressing "skipping" log lines (by default?)

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/copywrite#19]
## Context

Currently `copywrite headers` can be quite chatty on bigger repositories, practically printing out every single file, esp. because it prints out the ones it skips. I can see how this can be useful for debugging!

I would argue though this is far less useful in day2day use, esp. when it's used to just add headers to a handful of new files. The new files just get drowned in the long output.

## Proposal

Allow suppressing/hiding the `cli: skipping:` log lines, or even making that the default option, with a `-verbose` or `-debug` flag to enable them.

**Comment by CalebAlbers** [comment]
This is a good idea, thanks for the suggestion!

Copywrite uses `hclog` and supports both `COPYWRITE_LOG_LEVEL=debug` and `RUNNER_DEBUG=1` env vars for triggering more verbose logging, so hiding the `skipping: %v` lines under that seems like a natural choice. I'll add it to our list of enhancement ideas.
