### ISSUE TITLE
Scope of tool

### ISSUE THREAD

**Issue by adam-moss** [hashicorp/copywrite#26]
Is the scope of this tool Hashicorp only?

The read me suggests it is intended to be generic, but there non-configurable items such as 

https://github.com/hashicorp/copywrite/blob/4cf18ec3f1cfc4864488d7735cb272c05541e779/cmd/license.go#L68

which bind it to Hashicorp.

Thanks!

**Comment by CalebAlbers** [comment]
Hey @adam-moss!

The scope is definitely for more than just HashiCorp, however the initial releases were from internal development and didn't have that functionality. That said, it was next up on my list and I went ahead and added #27, which allows you to set the copyright holder via command-line flag or in your `.copywrite.hcl` file.

There are a couple other places that are bound to HashiCorp (e.g., the `report` commands), but some follow-up PRs will be making those more general in the next couple weeks as well. That said, #27 should unblock 99% of external use cases.

Thanks again for the note!

**Comment by adam-moss** [comment]
Nice, thank you!
