### ISSUE TITLE
s390x Support

### ISSUE THREAD

**Issue by Joshua-Beha** [hashicorp/copywrite#68]
In an attempt to build the [Vault Secrets Operator](https://github.com/hashicorp/vault-secrets-operator) for s390x architecture, I ran into issues because copywrite does not support s390x but is required by VSO. Is s390x support possible/on the roadmap?

**Comment by CalebAlbers** [comment]
Hey @Joshua-Beha,

The Vault Secrets Operator doesn't have a runtime dependency on Copywrite - it only uses it as part of a Makefile target for adding copyright headers and license attestations during development. That said, I believe you should be able to comment out those lines from the Makefile and continue building VSO on s390x without waiting for Copywrite to add support (this is the first ask we've had for alternative architectures, and we don't have an s390x machine to test with).

**Comment by Joshua-Beha** [comment]
Hmm ok, thanks for the info!
