### ISSUE TITLE
autodiscover ignores discovery errors

### ISSUE THREAD

**Issue by brandonc** [hashicorp/copywrite#9]
I ran copywrite init without a LICENSE file and hit a panic. I was able to work around by specifying --spdx flag. I noticed [here](https://github.com/hashicorp/copywrite/blob/main/cmd/init.go#L71-L85):

- *data may be nil if an error is returned from Get
- GetLicense() may return nil if no LICENSE is added to the repo yet

**Comment by CalebAlbers** [comment]
Thanks for the bug report, @brandonc! I was able to reproduce on my end and will get a fix in this afternoon.

**Comment by CalebAlbers** [comment]
@brandonc a fix shipped in v0.13.2

Feel free to re-open if you re-encounter the bug. Thanks again for reporting it!
